// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inv.reg.ped.online.models;

namespace inv.reg.ped.online.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250313235238_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("inv.reg.ped.online.models.Pedidos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Corrreo")
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<int>("SaldoFaltante")
                        .HasColumnType("int");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdVenta");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("inv.reg.ped.online.models.Productos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadEnB")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad en B");

                    b.Property<int>("CantidadMin")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad Min");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("inv.reg.ped.online.models.UnidadesVendidas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CantidadVendida")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("UnidadesVendedidas");
                });

            modelBuilder.Entity("inv.reg.ped.online.models.Ventas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CodTransaccion")
                        .HasColumnType("int");

                    b.Property<int>("Recaudo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("inv.reg.ped.online.models.Pedidos", b =>
                {
                    b.HasOne("inv.reg.ped.online.models.Ventas", "Venta")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("inv.reg.ped.online.models.UnidadesVendidas", b =>
                {
                    b.HasOne("inv.reg.ped.online.models.Productos", "Producto")
                        .WithMany("UnidadesVendidas")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inv.reg.ped.online.models.Ventas", "Venta")
                        .WithMany("UnidadesVendidas")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("inv.reg.ped.online.models.Productos", b =>
                {
                    b.Navigation("UnidadesVendidas");
                });

            modelBuilder.Entity("inv.reg.ped.online.models.Ventas", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("UnidadesVendidas");
                });
#pragma warning restore 612, 618
        }
    }
}
